// <auto-generated />
using APEC.DAL.SQL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace APEC.Migrations
{
    [DbContext(typeof(ApecDbContext))]
    partial class ApecDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("APEC.Entity.Nomina", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaveNomina");

                    b.Property<string>("Cuenta");

                    b.Property<decimal>("MontoPagar");

                    b.Property<string>("NoDocumento");

                    b.Property<string>("TipoDocumento");

                    b.Property<string>("TipoRegistro");

                    b.HasKey("Id");

                    b.ToTable("Nominas");
                });
#pragma warning restore 612, 618
        }
    }
}
